name: Remove - LeetSync from Commit Message

on:
  push:
    branches:
      - main

jobs:
  remove-leetsync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove - LeetSync from commit message
      run: |
        git filter-branch -f --msg-filter '
          sed "s/- LeetSync//g"
        ' HEAD

    - name: Force push changes
      run: |
        git push origin main --force
